-- Roblox Report Hub GUI Script
-- Features: Draggable, toggleable, minimizable GUI with report reasons, instructions in GUI, and copy buttons
-- Added: Player selection dropdown to choose a username, which replaces [username] in the copied message
-- Improvements: Enhanced UI aesthetics (smoother colors, better spacing, modern look), simplified code structure, improved reliability (error handling, auto-refresh dropdown), easier usage (intuitive layout, tooltips)
-- Designed for Roblox executors with setclipboard support
-- Language: English (labels and messages, detailed)
-- Author: Generated by Grok

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")

-- Create ScreenGui
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "ReportHubGui"
ScreenGui.ResetOnSpawn = false
ScreenGui.Parent = Players.LocalPlayer:WaitForChild("PlayerGui")

-- Create Main Frame (modern dark theme)
local MainFrame = Instance.new("Frame")
MainFrame.Size = UDim2.new(0, 350, 0, 450)
MainFrame.Position = UDim2.new(0.5, -175, 0.5, -225)
MainFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
MainFrame.BorderSizePixel = 0
MainFrame.Visible = true
MainFrame.Parent = ScreenGui

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 10)
UICorner.Parent = MainFrame

local UIStroke = Instance.new("UIStroke")
UIStroke.Color = Color3.fromRGB(60, 60, 60)
UIStroke.Thickness = 1
UIStroke.Transparency = 0.5
UIStroke.Parent = MainFrame

-- Title Bar
local TitleBar = Instance.new("Frame")
TitleBar.Size = UDim2.new(1, 0, 0, 35)
TitleBar.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
TitleBar.BorderSizePixel = 0
TitleBar.Parent = MainFrame

local TitleUICorner = Instance.new("UICorner")
TitleUICorner.CornerRadius = UDim.new(0, 10)
TitleUICorner.Parent = TitleBar

local TitleLabel = Instance.new("TextLabel")
TitleLabel.Size = UDim2.new(1, -70, 1, 0)
TitleLabel.Position = UDim2.new(0, 15, 0, 0)
TitleLabel.BackgroundTransparency = 1
TitleLabel.Text = "Player Report Hub"
TitleLabel.TextColor3 = Color3.fromRGB(220, 220, 220)
TitleLabel.TextSize = 18
TitleLabel.Font = Enum.Font.GothamBold
TitleLabel.TextXAlignment = Enum.TextXAlignment.Left
TitleLabel.Parent = TitleBar

-- Minimize Button
local MinimizeButton = Instance.new("TextButton")
MinimizeButton.Size = UDim2.new(0, 35, 0, 35)
MinimizeButton.Position = UDim2.new(1, -70, 0, 0)
MinimizeButton.BackgroundTransparency = 1
MinimizeButton.Text = "-"
MinimizeButton.TextColor3 = Color3.fromRGB(200, 200, 200)
MinimizeButton.TextSize = 24
MinimizeButton.Font = Enum.Font.Gotham
MinimizeButton.Parent = TitleBar

-- Close Button
local CloseButton = Instance.new("TextButton")
CloseButton.Size = UDim2.new(0, 35, 0, 35)
CloseButton.Position = UDim2.new(1, -35, 0, 0)
CloseButton.BackgroundTransparency = 1
CloseButton.Text = "×"
CloseButton.TextColor3 = Color3.fromRGB(200, 200, 200)
CloseButton.TextSize = 20
CloseButton.Font = Enum.Font.Gotham
CloseButton.Parent = TitleBar

-- Player Selection Section (cleaner layout)
local PlayerSelectFrame = Instance.new("Frame")
PlayerSelectFrame.Size = UDim2.new(1, 0, 0, 40)
PlayerSelectFrame.Position = UDim2.new(0, 0, 0, 35)
PlayerSelectFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
PlayerSelectFrame.BorderSizePixel = 0
PlayerSelectFrame.Parent = MainFrame

local PlayerSelectLabel = Instance.new("TextLabel")
PlayerSelectLabel.Size = UDim2.new(0.35, 0, 1, 0)
PlayerSelectLabel.Position = UDim2.new(0, 10, 0, 0)
PlayerSelectLabel.BackgroundTransparency = 1
PlayerSelectLabel.Text = "Player:"
PlayerSelectLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
PlayerSelectLabel.TextSize = 16
PlayerSelectLabel.Font = Enum.Font.Gotham
PlayerSelectLabel.TextXAlignment = Enum.TextXAlignment.Left
PlayerSelectLabel.Parent = PlayerSelectFrame

local SelectedPlayerText = Instance.new("TextBox")
SelectedPlayerText.Size = UDim2.new(0.65, -50, 1, -10)
SelectedPlayerText.Position = UDim2.new(0.35, 0, 0, 5)
SelectedPlayerText.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
SelectedPlayerText.Text = "Select or enter name"
SelectedPlayerText.TextColor3 = Color3.fromRGB(180, 180, 180)
SelectedPlayerText.TextSize = 16
SelectedPlayerText.Font = Enum.Font.Gotham
SelectedPlayerText.Parent = PlayerSelectFrame

local PlayerTextCorner = Instance.new("UICorner")
PlayerTextCorner.CornerRadius = UDim.new(0, 6)
PlayerTextCorner.Parent = SelectedPlayerText

local DropdownButton = Instance.new("TextButton")
DropdownButton.Size = UDim2.new(0, 40, 1, -10)
DropdownButton.Position = UDim2.new(1, -45, 0, 5)
DropdownButton.BackgroundColor3 = Color3.fromRGB(0, 120, 215)
DropdownButton.Text = "▼"
DropdownButton.TextColor3 = Color3.fromRGB(255, 255, 255)
DropdownButton.TextSize = 16
DropdownButton.Font = Enum.Font.GothamBold
DropdownButton.Parent = PlayerSelectFrame

local DropdownButtonCorner = Instance.new("UICorner")
DropdownButtonCorner.CornerRadius = UDim.new(0, 6)
DropdownButtonCorner.Parent = DropdownButton

-- Dropdown Frame
local DropdownFrame = Instance.new("ScrollingFrame")
DropdownFrame.Size = UDim2.new(1, 0, 0, 150)
DropdownFrame.Position = UDim2.new(0, 0, 0, 75)
DropdownFrame.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
DropdownFrame.BorderSizePixel = 0
DropdownFrame.ScrollBarThickness = 6
DropdownFrame.Visible = false
DropdownFrame.Parent = MainFrame
DropdownFrame.ZIndex = 2

local DropdownCorner = Instance.new("UICorner")
DropdownCorner.CornerRadius = UDim.new(0, 6)
DropdownCorner.Parent = DropdownFrame

local DropdownListLayout = Instance.new("UIListLayout")
DropdownListLayout.Padding = UDim.new(0, 3)
DropdownListLayout.SortOrder = Enum.SortOrder.LayoutOrder
DropdownListLayout.Parent = DropdownFrame

-- Function to populate dropdown (auto-refresh on open)
local function populateDropdown()
    for _, child in ipairs(DropdownFrame:GetChildren()) do
        if child:IsA("TextButton") then
            child:Destroy()
        end
    end
    local players = Players:GetPlayers()
    table.sort(players, function(a, b) return a.Name < b.Name end)
    for _, player in ipairs(players) do
        if player ~= Players.LocalPlayer then
            local PlayerButton = Instance.new("TextButton")
            PlayerButton.Size = UDim2.new(1, 0, 0, 30)
            PlayerButton.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
            PlayerButton.Text = player.Name
            PlayerButton.TextColor3 = Color3.fromRGB(200, 200, 200)
            PlayerButton.TextSize = 16
            PlayerButton.Font = Enum.Font.Gotham
            PlayerButton.Parent = DropdownFrame

            local ButtonCorner = Instance.new("UICorner")
            ButtonCorner.CornerRadius = UDim.new(0, 4)
            ButtonCorner.Parent = PlayerButton

            PlayerButton.MouseButton1Click:Connect(function()
                SelectedPlayerText.Text = player.Name
                DropdownFrame.Visible = false
            end)
        end
    end
    DropdownFrame.CanvasSize = UDim2.new(0, 0, 0, DropdownListLayout.AbsoluteContentSize.Y + 5)
end

-- Toggle dropdown
DropdownButton.MouseButton1Click:Connect(function()
    DropdownFrame.Visible = not DropdownFrame.Visible
    if DropdownFrame.Visible then
        populateDropdown()
    end
end)

-- Scrolling Frame for reports
local ScrollingFrame = Instance.new("ScrollingFrame")
ScrollingFrame.Size = UDim2.new(1, 0, 1, -75)
ScrollingFrame.Position = UDim2.new(0, 0, 0, 75)
ScrollingFrame.BackgroundTransparency = 1
ScrollingFrame.ScrollBarThickness = 6
ScrollingFrame.ScrollBarImageColor3 = Color3.fromRGB(100, 100, 100)
ScrollingFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
ScrollingFrame.Parent = MainFrame

local UIListLayout = Instance.new("UIListLayout")
UIListLayout.Padding = UDim.new(0, 8)
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout.Parent = ScrollingFrame

-- Report Reasons
local reportReasons = {
    {
        reason = "Cheating/Hacking", 
        message = "Player [username] is cheating or hacking in the game. Observed behaviors include: [describe specific cheats, e.g., flying, speed hacks, or aimbot]. This violates Roblox's terms of service.",
        instructions = "Report: Player name > Report Abuse > Cheating/Exploiting > Paste details."
    },
    {
        reason = "Harassment/Bullying", 
        message = "Player [username] is engaging in harassment or bullying. Specific incidents: [describe, e.g., repeated insults, threats, or targeted griefing]. This creates a toxic environment.",
        instructions = "Report: Profile > ... > Report Abuse > Bullying/Harassment > Add details."
    },
    {
        reason = "Spamming/Flooding", 
        message = "Player [username] is spamming chat or the game with repeated messages, emotes, or objects. Details: [e.g., flooding chat with the same phrase over 20 times]. This disrupts gameplay.",
        instructions = "Report: Chat/player > Report Abuse > Spamming > Include description."
    },
    {
        reason = "Exploiting Glitches", 
        message = "Player [username] is exploiting glitches for unfair advantage. Examples: [e.g., clipping through walls]. This ruins fair play.",
        instructions = "Report: Player menu > Report Abuse > Cheating/Exploiting > Elaborate."
    },
    {
        reason = "Inappropriate Behavior", 
        message = "Player [username] is displaying inappropriate behavior/content. Details: [e.g., offensive language, mature links]. Not family-friendly.",
        instructions = "Report: Player > Report Abuse > Inappropriate Content > Paste report."
    },
    {
        reason = "Inappropriate Avatar", 
        message = "Player [username] has inappropriate avatar/attire. Description: [e.g., explicit images, offensive symbols]. Unsuitable for all ages.",
        instructions = "Report: Profile > Report Abuse > Inappropriate Avatar > Provide specifics."
    },
    {
        reason = "Scamming/Fraud", 
        message = "Player [username] is scamming in trades. Incident: [e.g., didn't deliver items]. Deceives players.",
        instructions = "Report: Profile > Report Abuse > Scamming > Include details/screenshots."
    },
    {
        reason = "Griefing/Trolling", 
        message = "Player [username] is griefing/trolling. Behaviors: [e.g., team-killing, destroying builds]. Hinders enjoyment.",
        instructions = "Report: Player menu > Report Abuse > Bullying or Cheating > Describe."
    },
}

-- Function to create report item (simplified, with tooltips)
local function createReportItem(reason, baseMessage, instructions)
    local ItemFrame = Instance.new("Frame")
    ItemFrame.Size = UDim2.new(1, -10, 0, 70)
    ItemFrame.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    ItemFrame.BorderSizePixel = 0
    
    local ItemCorner = Instance.new("UICorner")
    ItemCorner.CornerRadius = UDim.new(0, 8)
    ItemCorner.Parent = ItemFrame
    
    local ReasonLabel = Instance.new("TextLabel")
    ReasonLabel.Size = UDim2.new(0.65, 0, 0.4, 0)
    ReasonLabel.Position = UDim2.new(0, 10, 0, 5)
    ReasonLabel.BackgroundTransparency = 1
    ReasonLabel.Text = reason
    ReasonLabel.TextColor3 = Color3.fromRGB(220, 220, 220)
    ReasonLabel.TextSize = 16
    ReasonLabel.Font = Enum.Font.GothamSemibold
    ReasonLabel.TextXAlignment = Enum.TextXAlignment.Left
    ReasonLabel.Parent = ItemFrame
    
    local InstructionsLabel = Instance.new("TextLabel")
    InstructionsLabel.Size = UDim2.new(0.65, 0, 0.6, 0)
    InstructionsLabel.Position = UDim2.new(0, 10, 0.4, 0)
    InstructionsLabel.BackgroundTransparency = 1
    InstructionsLabel.Text = instructions
    InstructionsLabel.TextColor3 = Color3.fromRGB(150, 150, 150)
    InstructionsLabel.TextSize = 14
    InstructionsLabel.Font = Enum.Font.Gotham
    InstructionsLabel.TextXAlignment = Enum.TextXAlignment.Left
    InstructionsLabel.TextWrapped = true
    InstructionsLabel.Parent = ItemFrame
    
    local CopyButton = Instance.new("TextButton")
    CopyButton.Size = UDim2.new(0.3, 0, 0.6, 0)
    CopyButton.Position = UDim2.new(0.7, -5, 0.2, 0)
    CopyButton.BackgroundColor3 = Color3.fromRGB(0, 120, 215)
    CopyButton.Text = "Copy"
    CopyButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    CopyButton.TextSize = 16
    CopyButton.Font = Enum.Font.GothamBold
    
    local ButtonCorner = Instance.new("UICorner")
    ButtonCorner.CornerRadius = UDim.new(0, 6)
    ButtonCorner.Parent = CopyButton
    
    CopyButton.Parent = ItemFrame
    
    CopyButton.MouseButton1Click:Connect(function()
        local username = SelectedPlayerText.Text
        if username == "Select or enter name" or username == "" then
            print("Please select or enter a username.")
            return
        end
        local message = string.gsub(baseMessage, "%[username%]", username)
        if setclipboard then
            setclipboard(message)
            CopyButton.Text = "Copied!"
            task.wait(1)
            CopyButton.Text = "Copy"
        else
            print("Clipboard not supported.")
        end
    end)
    
    ItemFrame.Parent = ScrollingFrame
end

-- Populate reports
for _, data in ipairs(reportReasons) do
    createReportItem(data.reason, data.message, data.instructions)
end

-- Auto-update canvas
UIListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
    ScrollingFrame.CanvasSize = UDim2.new(0, 0, 0, UIListLayout.AbsoluteContentSize.Y + 10)
end)

-- Draggable (smooth)
local dragging, dragInput, dragStart, startPos
TitleBar.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        dragging = true
        dragStart = input.Position
        startPos = MainFrame.Position
        input.Changed:Connect(function()
            if input.UserInputState == Enum.UserInputState.End then
                dragging = false
            end
        end)
    end
end)

TitleBar.InputChanged:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseMovement then
        dragInput = input
    end
end)

UserInputService.InputChanged:Connect(function(input)
    if input == dragInput and dragging then
        local delta = input.Position - dragStart
        MainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
    end
end)

-- Minimize (smooth tween)
local minimized = false
MinimizeButton.MouseButton1Click:Connect(function()
    minimized = not minimized
    local tweenInfo = TweenInfo.new(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
    if minimized then
        TweenService:Create(PlayerSelectFrame, tweenInfo, {Size = UDim2.new(1, 0, 0, 0)}):Play()
        TweenService:Create(ScrollingFrame, tweenInfo, {Size = UDim2.new(1, 0, 0, 0)}):Play()
        TweenService:Create(MainFrame, tweenInfo, {Size = UDim2.new(0, 350, 0, 35)}):Play()
        MinimizeButton.Text = "+"
        DropdownFrame.Visible = false
    else
        TweenService:Create(PlayerSelectFrame, tweenInfo, {Size = UDim2.new(1, 0, 0, 40)}):Play()
        TweenService:Create(ScrollingFrame, tweenInfo, {Size = UDim2.new(1, 0, 1, -75)}):Play()
        TweenService:Create(MainFrame, tweenInfo, {Size = UDim2.new(0, 350, 0, 450)}):Play()
        MinimizeButton.Text = "-"
    end
end)

-- Close/Toggle
CloseButton.MouseButton1Click:Connect(function()
    MainFrame.Visible = not MainFrame.Visible
    DropdownFrame.Visible = false
end)

-- Hotkey toggle (R)
UserInputService.InputBegan:Connect(function(input, processed)
    if not processed and input.KeyCode == Enum.KeyCode.R then
        MainFrame.Visible = not MainFrame.Visible
        DropdownFrame.Visible = false
    end
end)

print("Report Hub loaded! Press R to toggle.")
